# Generated by Django 2.2.12 on 2009-08-21 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name="Nom de l'ingredien")),
                ('photo', models.ImageField(null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Ingredien',
            },
        ),
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='Quantité')),
                ('designation', models.CharField(max_length=10, null=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recips.Ingredient')),
            ],
            options={
                'verbose_name': 'Quantité',
            },
        ),
        migrations.CreateModel(
            name='Recip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la recette')),
                ('indication', models.TextField(verbose_name='Description de la recette')),
                ('photo', models.ImageField(null=True, upload_to='')),
                ('persons', models.IntegerField(null=True, verbose_name='Nombre de personne')),
                ('date', models.DateField(auto_now=True, verbose_name="Date d'ajout")),
                ('ingredient_quantity', models.ManyToManyField(related_name='_recip_ingredient_quantity_+', through='recips.Quantity', to='recips.Ingredient', verbose_name='Ingredient avc quantité')),
                ('ingredients', models.ManyToManyField(related_name='recettes', to='recips.Ingredient')),
            ],
            options={
                'verbose_name': 'Recette',
            },
        ),
        migrations.AddField(
            model_name='quantity',
            name='recip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recips.Recip'),
        ),
    ]
