# Generated by Django 2.2.12 on 2009-08-17 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recips', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ingredient'},
        ),
        migrations.RenameField(
            model_name='recip',
            old_name='indication',
            new_name='preparation',
        ),
        migrations.RemoveField(
            model_name='recip',
            name='ingredient_quantity',
        ),
        migrations.AddField(
            model_name='recip',
            name='persons_number',
            field=models.IntegerField(null=True),
        ),
        migrations.RemoveField(
            model_name='recip',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recip',
            name='ingredients',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Quantity',
        ),
    ]
