# Generated by Django 2.2.12 on 2020-07-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recips', '0003_auto_20200708_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.URLField(null=True),
        ),
    ]
